github/secure_headers

Gemfile

Should probably just :fire: 1.8.7 support but this works.

Make yet another exception for 1.8.7

---

lib/secure_headers/view_helper.rb

Including `SecureHeaders::ViewHelpers` directly into `ActionView::Helpers` does *not* make them available in views in Rails 4.2. Including the helper module directly into `ActionView::Base` makes them available.
I'm not sure if this is going to fly in Rails 3.x, will have to wait for the results from Travis.

Include ActionView helpers in ActionView::Base

---

README.md
lib/secure_headers.rb
lib/secure_headers/headers/public_key_pins.rb
spec/lib/secure_headers/headers/public_key_pins_spec.rb
spec/lib/secure_headers_spec.rb
spec/spec_helper.rb

I've added support for HPKP headers now that it is supported in both Chrome and Firefox.

Add HPKP support

---

README.md
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Without this, the code executes in the context of `SecureHeaders::Configuration:Module` which is pretty useless.
e.g.
```
:enforce => lambda { |controller| controller.current_user.beta_testing? }
```
This is kind of a breaking change, if `lambda`s were using instead of `proc`s since the lambda enforces the passed in value.

Pass reference to controller to CSP callable config values

---

fixtures/rails_3_2_12/spec/controllers/other_things_controller_spec.rb
fixtures/rails_4_1_8/spec/controllers/other_things_controller_spec.rb
lib/secure_headers/headers/content_security_policy.rb
secure_headers.gemspec
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Because safari pukes when it sees a nonce. it still works (falls back to `unsafe-inline`) but it's unsightly. 
/cc @maddox

Sniff for nonce support

---

lib/secure_headers.rb

Based on the thread from #146
This will help with:
- Allowing a controller to use instance data e.g. `current_user`
- Allowing a controller instance to override the default keys set in `::SecureHeaders::Configuration.configure`

Change `options_for` from class method to instance method

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

The current behavior results in a data URI being appended to the ```img-src``` directive regardless of whether or not the user actually wants to allow data URIs. This PR introduced a new configuration option that the user can specify in order to disable the auto-whitelisting.

Allow user to disable auto data uri whitelist

---

README.md

I just fixed a small typo in the README.md file for the name of our library.

Fixed a small typo in the name

---

README.md
lib/secure_headers.rb
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/public_key_pins.rb
lib/secure_headers/headers/strict_transport_security.rb
lib/secure_headers/headers/x_content_type_options.rb
lib/secure_headers/headers/x_download_options.rb
lib/secure_headers/headers/x_frame_options.rb
lib/secure_headers/headers/x_permitted_cross_domain_policies.rb
lib/secure_headers/headers/x_xss_protection.rb
spec/lib/secure_headers_spec.rb

Accepts a hash for overrides, but defaults to app config.
See discussion in https://github.com/twitter/secureheaders/issues/167
/cc @rlwinter @TiagoCardoso1983

SecureHeaders as a rack middleware 

---

README.md

@twitter, I've corrected a typographical error in the documentation of the [secureheaders](https://github.com/twitter/secureheaders) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

Fixed typographical error, changed authorites to authorities in README.

---

README.md
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy/script_hash_middleware_spec.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers_spec.rb

Fixes https://github.com/twitter/secureheaders/issues/169
Adds a deprecation warning too.

remove examples that use inline/eval over 'unsafe-inline'/'unsafe-eval'

---

README.md
fixtures/rails_3_2_22/config/initializers/secure_headers.rb
fixtures/rails_3_2_22_no_init/app/controllers/other_things_controller.rb
fixtures/rails_4_1_8/config/initializers/secure_headers.rb
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

1. This should not be required since browsers should implement the `effective-directive` portion of the spec.
1. Managing what is considered an inherited value for the various browser versions can get tricky (see https://github.com/twitter/secureheaders/issues/170).
1. It's not that hard to do the same thing manually
1. It somewhat encourages lazy, over permissive policies.

Remove the 'fill missing directives with default-src value' feature

---

Gemfile
README.md
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/view_helper.rb
spec/lib/secure_headers/headers/content_security_policy/script_hash_middleware_spec.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers_spec.rb

Integrating the browser sniffing / directive use that GitHub uses internally. Use the UA to determine which directives should be supported. Provides better validation of config values.

Ua sniffing for support

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

In an attempt to perform strict validation on the values passed into secureheaders configs, I forgot that I was mutating global state.
Fixes #183

fix regression with mutation of global state

---

lib/secure_headers.rb
spec/lib/secure_headers_spec.rb

The `header_hash` opt-out code was not consistent with the non-header-hash code. Mainly opting out of a header meant you would get an exception:
```
NoMethodError:
undefined method `name' for nil:NilClass
```
I'm going to see if this issue exists on the 3.x branch as well.
/cc @moratorius

Fix issue with opting out of headers when using header_hash method

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

We ran into an error where a nil value wouldn't pass the ["arrays of strings" validation test](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/headers/content_security_policy.rb#L251). This came up when doing environment-specific configuration where values would be `nil` without `compact`ing the array.
While testing this out, I also noticed that an empty array or array of `nil`s (`[nil]` which is compacted) would include the directive, but without any value. `script_src: [nil]` would produce `script-src ;`. That's bad.
Also, I noticed that the [code that minifies directives containing `*`](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/headers/content_security_policy.rb#L336) was incorrectly discarding `data:` and `blob:` which are not …

Handle nil values and empty arrays

---

lib/secure_headers/view_helper.rb

This will make it so you do not need to supply options for it to work, just setting it to nil or a blank string causes a error when you try to merge the nonce.

added `to_h` to nonced_tag in view helper

---

.travis.yml
Gemfile
Guardfile
fixtures/rails_3_2_22_no_init/app/controllers/other_things_controller.rb
lib/secure_headers.rb
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/strict_transport_security.rb
lib/secure_headers/headers/x_content_type_options.rb
lib/secure_headers/headers/x_download_options.rb
lib/secure_headers/headers/x_frame_options.rb
lib/secure_headers/headers/x_permitted_cross_domain_policies.rb
lib/secure_headers/headers/x_xss_protection.rb
lib/secure_headers/version.rb
secure_headers.gemspec
spec/lib/secure_headers/headers/x_content_type_options_spec.rb
spec/lib/secure_headers/headers/x_xss_protection_spec.rb
spec/lib/secure_headers_spec.rb

Update the 2.x branch with deprecation warnings for upgrading to the 3.x branch. 
Lots of things will break with the new major release, almost all of which should be covered by these deprecation warnings. A post install message provides a link to the migration document: https://github.com/twitter/secureheaders/blob/master/upgrading-to-3-0.md
This _should_ cover everything and these changes should be forward compatible with 3.x.

2.x deprecation warnings

---

README.md

Minor change to documentation. The sinatra example had configure instead of default. Also, the documentation below is for the 3.x branch but it says it's for 2.x.

Updating readme with correct sinatra config

---

lib/secure_headers.rb
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

This adds the `#idempotent_additions?` method to the CSP class for determining whether `config` will change at all after `additions` are merged into the config. 
The `override/append_content_security_policy_directive` methods are wrapped in a call to `idempotent_additions?` before the configuration object is modified. Modifying the configuration object causes it to discard the precomputed header values. If the change has no effect, then there's no reason to blow away the cache.

If a policy modification is idempotent, don't dup the config

---

README.md
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Before this change, all schemes were stripped from host sources. This is because modern browsers know that on an HTTPS resource, only HTTPS is allowed but on HTTP resources, both HTTP and HTTPS are allowed. Safari on the other hand doesn't support this. In an ideal world, all local development would be over HTTPS and there would never be a need to serve/load HTTP resources.
Adding `:preserve_schemes` (defaults to false) unfortunately also allows mixed content. i.e. If you are on an HTTPS resource, but you've whitelisted an HTTP resource you have allowed mixed content.
The 2.x series does not remove any schemes.

Add CSP config flag to preserve host source schemes

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Supplying a directive with a value of `nil` could :boom: in two places:
* During `idempotent_additions?` check
* When generating the header

Directive values may be nil, so secure_headers should not :boom:

---

lib/secure_headers.rb

This should allow use of Rails 5 without deprecations from `before_filter`.
`before_filter` is deprecated and will be removed in Rails 5.1.
I know the use of before_* at all has been removed from the 3.x release, but as that's not stable yet I think this is a good way to go.

2.x maintenance: Use before_action if possible, for Rails 5 support

---

README.md
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

In my testing, firefox and chrome (and opera) support this value. Safari, untested.
Fixes #219
/cc @reedloden

Add support for CSP upgrade-insecure-requests source expression

---

upgrading-to-3-0.md

I think the 2.x → 3.x upgrade instructions are missing a step: "remove the `ensure_security_headers` from your controllers."

Remove ensure_security_headers for 3.x upgrade

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Previously, this would cause an exception:
```
RuntimeError:
can't modify frozen Hash
```

Handle frozen hashes

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Previously, non default source values would be merged with the default-src value which makes no sense. This was especially confusing if your default-src was `*` or `'none'`
I'm going to wait until I confirm that `plugin-types` is a non-default source directive. The spec does not mention it explicitly, and I've submitted https://github.com/w3c/webappsec/pull/510 in case my hunch is correct.

Handle policy merges when directives do not inherit from default-src

---

lib/secure_headers.rb
lib/secure_headers/configuration.rb
lib/secure_headers/middleware.rb
lib/secure_headers/railtie.rb
spec/lib/secure_headers/configuration_spec.rb
spec/lib/secure_headers/middleware_spec.rb

See #145 for initial discussion
We would like to give users the ability to flag all cookies as secure: https://www.owasp.org/index.php/SecureFlag

Secure Cookies

---

lib/secure_headers.rb
lib/secure_headers/configuration.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/configuration_spec.rb
spec/lib/secure_headers/middleware_spec.rb
spec/lib/secure_headers_spec.rb

Fixes #217 
Currently, an idempotency check is performed for every policy addition. Not only does this create a fair number of temporary objects, but it also busts the entire header cache if any changes are detected.
This change defers idempotency checks until just before the header values are generated. If we can determine that the CSP will differ from the cached values, we discard all cached CSP and generate one specific to that UA.
If there is a change to `X-Frame-Options`, we cache the new value immediately.
As a result, the value for `cached_headers` will always maintain the headers that will be applied and there is no need to generate them when calling `header_hash_for`. 
Because we are retaining the previously discarded cached headers, we only call `dup` on the configuration option …

Handle very dynamic policies better

---

lib/secure_headers/configuration.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers_spec.rb

`idempotent_additions?` would return false when comparing `OPT_OUT` with `OPT_OUT`, causing `header_hash_for` to return a header cache with `{ nil => nil }` which cause the middleware to blow up when `{ nil => nil }` was merged into the rack header hash. 
This is a regression in 3.1.0 only.
Now it returns true. I've added a test case to ensure that `header_hash_for` will never return such an element.

Opting out of all protection would raise an exception because the idempotency check was wrong

---

lib/secure_headers/configuration.rb
spec/lib/secure_headers/configuration_spec.rb
spec/lib/secure_headers_spec.rb

This meant that when header caches were regenerated upon calling `SecureHeaders.override(:name)` and using it with `use_secure_headers_override` would result in default values for anything other than CSP/HPKP.

Regression: overrides were not carrying configuration values forward

---

README.md
lib/secure_headers.rb
lib/secure_headers/configuration.rb
lib/secure_headers/headers/referrer_policy.rb
lib/secure_headers/railtie.rb
spec/lib/secure_headers/headers/referrer_policy_spec.rb
spec/lib/secure_headers_spec.rb
spec/spec_helper.rb

See #218 for initial discussion.  Forgot to check browser support before going ahead with this 😞 Maybe useful at a later date.

Add support for Referrer Policy header

---

README.md
lib/secure_headers/configuration.rb
lib/secure_headers/middleware.rb
spec/lib/secure_headers/middleware_spec.rb

Fixes https://github.com/twitter/secureheaders/issues/166

Warn if HPKP report host is the same as the current host

---

README.md
lib/tasks/tasks.rake

I just tested the gem and came across these minor papercuts.
- Fix minor papercuts in README.
- Add description to rake task to make it appear in `rake -T`.
Another thing I was wondering about was that it appears `frame_src` is deprecated (according to http://content-security-policy.com/), so does it make sense to remove it from the example in the README?
Thanks!

Fix minor papercuts

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

I was using `upgrade_insecure_requests: false` but I still got `upgrade-insecure-requests` in my header. It would appear this is a bug?

Fix false booleans being included in the CSP directive

---

lib/tasks/tasks.rake

Signed-off-by: Dan Kohn <dan@dankohn.com>
This is an alternative fix to #258. It also resolves #257 and addresses the comment https://github.com/twitter/secureheaders/pull/258#issuecomment-219264431 by @jacobbednarz.

Alternative fix for already initialized constant

---

lib/secure_headers/view_helper.rb

When using rspec with rails-controller-testing, specs would break due to incorrect load order. More info here: https://github.com/rails/rails-controller-testing/issues/24

hook include of helper to loading of ActionView

---

README.md
lib/secure_headers.rb
lib/secure_headers/configuration.rb
spec/lib/secure_headers_spec.rb

Fixes #250
@reedloden was this what you had in mind?
This allows you to define blocks of code that produce a hash of additions to be added to the CSP for a given request. The current request object is passed to the block. The result of the hash is passed to `append_content_security_policy_directives`.
The use case _usually_ is related to loosening a policy's restrictions. While we do provide `SecureHeaders::Configuration.override` blocks, something like this may be useful with `override_content_security_policy_directives` as well. I think that the demand for override support like this is pretty rare so I'll wait until there's a need. One example I can think of would be needing to override a directive with `'none'`, but chances are anything that needs to be set to `none` would be set in …

add support for named appends

---

README.md
lib/secure_headers.rb
lib/secure_headers/configuration.rb
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/configuration_spec.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb
spec/lib/secure_headers/middleware_spec.rb
spec/lib/secure_headers/view_helpers_spec.rb
spec/lib/secure_headers_spec.rb
spec/spec_helper.rb

Fixes #256, #281
Setting two headers has been an often requested feature that has always had a workaround but was never a first class feature. This PR allows setting both headers.
In the process of supporting both, I decided to move away from hash-backed configs and towards class-based configs - mostly because it made debugging things very hard and mistyping a hash key is far to easy. This has the added benefit of not having to perform "deep clones" all the time and relying on hash voodoo. This is much clearer even if some of the operations are just glorified hash operations. 
This also adds a `@modified` attribute which signals whether the cached headers can be used or not. This removes the need to track a `dynamic_csp`, choose between two configs, and use the `idempotent_operations` …

Setting two CSP headers, abstract out dynamic pieces

---

README.md

`csp_report_only` is available only in 3.5.0_pre and onwards, but if you run bundle install with `gem 'secure_headers`` in your Gemfile, it will pull 3.4.1 which doesn't have `csp_report_only` available.

Fixing README documentation on csp_report_only

---

Gemfile

This might fix the issues @lalithr95 is running into in https://github.com/twitter/secureheaders/pull/290

restrict term-ansicolor so it works on 1.9

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers_spec.rb
spec/spec_helper.rb

Use CSP nonces for Safari 10+ responses.

safari 10 supports nonces

---

lib/secure_headers.rb
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/policy_management.rb

Because this is helpful outside of SecureHeaders too.
This also re-adds `CSP = ContentSecurityPolicy` so you can references constants via `SecureHeaders::CSP`.

make the nonce support helper method public

---

lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

This is a potential fix for #299, I'm not too familiar with useragent versioning but this seems like it will work. I've tested it against `0.10.0` which is mentioned in the issue.
I'm also not really loving `VERSION_NIL` as a constant name but couldn't think of anything better. 🤔

handle null useragent version

---

lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Fixes #302 (don't fix it, just a partial implementation)
`'strict-dynamic'` was always supported since we don't do strict validation on source lists. This PR adds a constant and a test using it.
I chose not to add strict browser sniffing for now so UAs that don't support it might spit out an error message. The browser sniffing around nonces ensures that `strict-dynamic` + `nonce` will safely fallback to `unsafe-inline` when nonces aren't known to be supported.
Once I have information on how widely this is supported, I'll go back and add the sniffing to exclude the `strict-dynamic` from policies when unsupported.

quick and dirty strict-dynamic support'

---

Gemfile
lib/secure_headers.rb
lib/secure_headers/controller_extension.rb
lib/secure_headers/railtie.rb

When include ActionController::Base.include(::SecureHeaders) called from reiltie.rb,
SecuerHeaders.add_features not defined yet.
As a result class/instance methods won't added to ActionController::Base.
But introduced in commit 4aee15ef85c7413aa6718a1ec9ea82f843eb6d03

Restore Rails 2 support

---

README.md

See https://hstspreload.org/#opt-in

Remove `preload` from the default HSTS configuration in the README.

---

lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Safari starting version 10 [added support for CSP2](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html).

Added CSP2 support for Safari 10+

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

`frame-src` was un-deprecated: https://w3c.github.io/webappsec-csp/#changes-from-level-2
Therefore I think this warning should be removed.
* [ ✔️  ] Has tests
* [n/a?] Documentation updated

remove deprecation warning about frame_src

---

.rspec
CONTRIBUTING.md
lib/secure_headers.rb
lib/secure_headers/configuration.rb
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/policy_management.rb
lib/secure_headers/headers/public_key_pins.rb
spec/lib/secure_headers/view_helpers_spec.rb
spec/lib/secure_headers_spec.rb

I enabled warnings in one of my apps and saw that the secure_headers was the source of a number of warnings. This change enables warnings in rspec and fixes the existing warnings. I ran the test suite about 25-30 times to cover multiple seeds as possible, but there's a chance I still missed some.

Enable verbose mode in tests

---

CHANGELOG.md
README.md
lib/secure_headers/headers/clear_site_data.rb
secure_headers.gemspec
spec/lib/secure_headers/headers/clear_site_data_spec.rb

Per request from @mikewest [via twitter](https://twitter.com/mikewest/status/877149667909406723), this PR updates the format used in the `Clear-Site-Data` header to the current format. 
/cc @oreoshake for review

Update Clear-Site-Data to use the current spec format.

---

secure_headers.gemspec

As per #336, secure_headers actually **_needs_** a minimum version of useragent. `v0.15.0` is the earliest version in which all the tests pass. Before `v0.9.0` secure_headers is not useable at all. 
Please view #336 for full discussion.

Fixes #336  Pins dependency version of useragent

---

CHANGELOG.md
Gemfile
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/configuration_spec.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb
spec/lib/secure_headers_spec.rb
spec/spec_helper.rb

This handles the first two items from https://github.com/twitter/secureheaders/issues/286
> - Require `script-src` to be set. Missing `script-src`s inherit from `default-src`. In general `default-src` lists are far too permissive for something like `script-src`.
> - Require `object-src` to be set. See ⬆️ 
/cc @stve @jacobbednarz
CI isn't green yet, but it works on my machine

[4.x prep] Require a script-src, change default CSP

---

README.md
spec/lib/secure_headers/headers/policy_management_spec.rb

Sorry for this tiny PR. It basically just kills a _single_ typo in _two_ places.
🙇

The smallest typo in comments/README.md

---

docs/cookies.md
lib/secure_headers/headers/cookie.rb
lib/secure_headers/middleware.rb
lib/secure_headers/utils/cookies_config.rb
spec/lib/secure_headers/headers/cookie_spec.rb
spec/lib/secure_headers/middleware_spec.rb
spec/spec_helper.rb

Adds `secure` and `httponly` flags to cookies by default, targeting a 4.0 release tracked by #286. 
/CC @stve @oreoshake 
Should 4.0 also include `SameSite=Lax`? 
> [- Default cookies to secure, httponly, samsite=lax](https://github.com/twitter/secureheaders/issues/286#issuecomment-305678390)
(I'm not sure if I should add this to the actual CHANGELOG file b/c I don't know which release this will get pulled into)
> Adds `secure` and `httponly` flags to all cookies by default.

Adds secure, httponly, and SameSite=lax to cookies by default

---

lib/secure_headers/headers/cookie.rb
spec/lib/secure_headers/headers/cookie_spec.rb

Fixes #268 
It looks like setting `samesite: true` broke at some point or was never supported but in #268 it was clear that `Lax` is the more practical default.

Default samesite: true to mean SameSite=Lax instead of Strict

---

lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb

This was a breaking change in 4.x and not having a workaround kind of sucks. I immediately ran into a problem with our APIs CSP (`default-src 'none'`) and adding `script-src 'none'` made me feel like a bad person.
This uses the `OPT_OUT` value to bypass the `script-src` requirement. While falling back to `default-src` can be dangerous for webapps, it would just waste bytes for APIs.

allow opting out of script-src requirement

---

lib/secure_headers.rb
lib/secure_headers/middleware.rb
spec/lib/secure_headers/middleware_spec.rb

When we started requiring the use of `OPT_OUT` for cookie settings to mean "don't touch my cookies," the tests didn't catch the case where the secure flag cannot be set on non-https requests.
When `config[:secure]` executes, it calls the `[]` function which is wired to go `boom`. This bypasses that code block if the value of `config` is `OPT_OUT`.
/cc @anglinb

Prevent global cookie OPT_OUT from blowing up in middleware

---

CHANGELOG.md

This fixes the URL to the 'Upgrading to 4.0' document in the CHANGELOG.

Fixed URL to 'Upgrading to 4.0' document.

---

lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb

The prior behavior tends to default treat directives that are lists as "source lists". But, a source list kind of has specific behavior (ex. they support `*` to mean "all"). So, there are not meaningful for other lists such as `media-type` and `sandbox`. These directives have "lists", but they are unique to their usage. So, we shouldn't treat them like a source list. This PR adds support for `media-type` and `sandbox`. In particular it treats them as follows:
* `sandbox` - Can set a maximally strict policy using either `sandbox: true` or `sandbox: []`. Any other policy requires each element in the list to be of the form `allow-*`.
* `media-type` - Requires that each element in the list be of the form `type/subtype`. 
In addition the the above, I also (I think) simplified some of the …

Distinguish between source lists directives and non-source list directives

---

upgrading-to-4-0.md

The documentation for upgrading to 4.0 suggests using `OPT_OUT` for
cookie values you don't wish to set however this throws a `NameError`
```
NameError: uninitialized constant OPT_OUT
```
To correctly resolve the `OPT_OUT` value, we need to use the
`SecureHeaders` namespace.

Use `SecureHeaders` namespace for OPT_OUT docs

---

upgrading-to-4-0.md

I missed this in #361 but didn't notice until _after_ it was merged.

Add last missing `SecureHeaders` namespace fix for `OPT_OUT`

---

README.md
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb

Closes #357 
I'm not sure about Opera support.
`SecureHeaders::PolicyManagment::VARIATIONS` defines same directives in Chrome and Opera, 
but MDN says that Opera doesn't support it.
Other than that, I believe everything else is in order.

Support worker-src CSP directive

---

README.md
lib/secure_headers/configuration.rb
lib/secure_headers/middleware.rb
spec/lib/secure_headers/configuration_spec.rb

Cookie config needs a default

---

CHANGELOG.md
lib/secure_headers/headers/expect_certificate_transparency.rb
spec/lib/secure_headers/headers/expect_certificate_transparency_spec.rb

It seems like semicolons were maybe specified at some point, since various articles written (ex. https://scotthelme.co.uk/a-new-security-header-expect-ct/) use semicolon as the delimiter. But, in the current spec (https://tools.ietf.org/html/draft-ietf-httpbis-expect-ct), commas are used. 
/cc @oreoshake - Since we just deployed this, I think I can confirm the semi-colons aren't working, as I didn't see any expect-ct related data when querying chrome://net-internals/#hsts.

Update Expect-CT to use separator in spec

---

CHANGELOG.md
README.md
lib/secure_headers/headers/referrer_policy.rb
spec/lib/secure_headers/headers/referrer_policy_spec.rb

I've yet to hunt down that this is official supported by [the spec](https://www.w3.org/TR/referrer-policy/). But, it seems to be a thing :smile:. Double checking with @estark37 before merging.

Update Referrer-Policy to support multiple token values

---

docs/per_action_configuration.md
lib/secure_headers/view_helper.rb
spec/lib/secure_headers/view_helpers_spec.rb

Adds support for nonced versions of Rails' CSS, JavaScript and Webpacker link/include tags.
* nonced_stylesheet_link_tag
* nonced_javascript_include_tag
* nonced_javascript_pack_tag

Add nonced versions of Rails link/include tags

---

docs/per_action_configuration.md
lib/secure_headers/view_helper.rb
spec/lib/secure_headers/view_helpers_spec.rb

Equivalents were added in 1e81a0a.
This also fixes a bug preventing passing any arguments to these tags. Tests were updated with a sample to reflect this. I can split that into a separate PR or separate commits if you prefer.

Add missing `nonced_stylesheet_pack_tag`

---

Gemfile
lib/secure_headers.rb
lib/secure_headers/configuration.rb
lib/secure_headers/headers/clear_site_data.rb
spec/lib/secure_headers/configuration_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb
spec/lib/secure_headers/middleware_spec.rb
spec/lib/secure_headers/view_helpers_spec.rb

In prep for https://github.com/twitter/secureheaders/pull/383, this will deprecate the use of `Configuration#get` which is not meant to be a public API.
Because it's used internally all over, I added a flag to whitelist its use. I use the flag in tests to avoid any rails env checking.
This should only warn if application code is calling `get`. In the next version, we will instead expose a `dup` method that can be used [as described in @ptoomey3's comment](https://github.com/twitter/secureheaders/pull/383#issuecomment-363858684)

Deprecate Configuration#get

---

CHANGELOG.md
README.md
docs/upgrading-to-6-0.md
lib/secure_headers.rb
lib/secure_headers/configuration.rb
lib/secure_headers/headers/clear_site_data.rb
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/expect_certificate_transparency.rb
lib/secure_headers/headers/policy_management.rb
lib/secure_headers/headers/public_key_pins.rb
lib/secure_headers/headers/referrer_policy.rb
lib/secure_headers/headers/strict_transport_security.rb
lib/secure_headers/headers/x_content_type_options.rb
lib/secure_headers/headers/x_download_options.rb
lib/secure_headers/headers/x_frame_options.rb
lib/secure_headers/headers/x_permitted_cross_domain_policies.rb
lib/secure_headers/headers/x_xss_protection.rb
secure_headers.gemspec
spec/lib/secure_headers/configuration_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb
spec/lib/secure_headers/middleware_spec.rb
spec/lib/secure_headers/view_helpers_spec.rb
spec/lib/secure_headers_spec.rb
spec/spec_helper.rb

:warning: Work in progress ⚠️ 
This PR is very likely not yet ready for a full review. But, I wanted to push up the work in progress to get a sense of whether the direction of it is palatable, since I am introducing some relatively foundational changes that will definitely break some existing uses. 
#380 outlines a bug related to the current implementation of named overrides. There is an underlying assumption that named override is more or less a "fork" of a parent configuration. The parent configuration, at the point the override is defined, is duplicated and then the changes in the override are applied. The resulting configuration is statically stored in a class instance variable and can be retrieved when it is requested with `Configuration.get(:named_override`). Unfortunately, this …

Rewrite the entire notion of named overrides (breaking change)

---

docs/upgrading-to-6-0.md
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers_spec.rb

Fixes #381 
/cc @jasssonpet can you see if this resolves your issue?
This pull request stops guessing whether or not a UA supports nonces and relies on the backwards-compatible behavior of sending `'unsafe-inline'` with every `'nonce-`. 
The reason for sniffing was mostly because Safari < 9 would generate console messages about an unknown directive value (`nonce-*`). Safari 9 is two versions behind so in theory fewer people are using it. Given the bugs UA sniffing like this has caused, I'm less sympathetic to those on unsupported browsers craving a clean console.

unconditionally send nonces and unsafe-inline when working with nonces

---

lib/secure_headers/view_helper.rb
spec/lib/secure_headers/view_helpers_spec.rb

Rails 5.2 adds support for configuring a Content-Security-Policy header, including adding nonces to tags produced by the `javascript_tag` helper.
Unfortunately, Rails and this gem now both define a helper named `content_security_policy_nonce`:
https://github.com/rails/rails/blob/v5.2.0.rc2/actionpack/lib/action_controller/metal/content_security_policy.rb#L44
https://github.com/twitter/secureheaders/blob/v5.0.5/lib/secure_headers/view_helper.rb#L69
The Rails helper wins over the Secure Headers one, and helpers like `nonced_javascript_tag` currently raise this error on Rails 5.2:
ArgumentError: wrong number of arguments (given 1, expected 0)
By using a method with a different name internally, we avoid clashing with the Rails implementation, and `nonced_javascript_tag` works again.

Avoid calling content_security_policy_nonce internally

---

lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Add option to disable appending 'unsafe-inline' when using nonces

---

README.md

This was added in https://github.com/twitter/secure_headers/pull/404 but not added to the `README`.

Document `disable_nonce_backwards_compatibility`

---

docs/cookies.md
docs/upgrading-to-6-0.md

Without `SecureHeaders::`, this will raise `uninitialized constant` error, this Pull Request fixes it.

Fix references to OPT_OUT constant

---

lib/secure_headers/configuration.rb
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

Reported in https://github.com/twitter/secure_headers/issues/418 by @mvgijssel we allow semicolons in directive source list values. The semicolons act as delimiters in CSP leading to undesired and possibly malicious behavior.
I think this is a harmless way of addressing the issue but I've added a deprecation warning indicating it will break with the next release.

Escape semi colons in directive source lists

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

See https://github.com/twitter/secure_headers/issues/418 
I think there's a fair amount of people on the 3.x line, this is a backport of https://github.com/twitter/secure_headers/pull/419

Escape semi colons in directive source lists in 3.x releases

---

.travis.yml
Gemfile
lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

See https://github.com/twitter/secure_headers/issues/418
Backport of https://github.com/twitter/secure_headers/issues/419

escape semicolons by replacing them with spaces for 5.x line

---

.rubocop.yml
Gemfile

```
Post-install message from rubocop:
Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.
Put this in your Gemfile.
gem 'rubocop-performance'
And then execute:
$ bundle install
Put this into your .rubocop.yml.
require: rubocop-performance
```

Add rubocop-performance gem and config to fix deprecation message

---

docs/named_overrides_and_appends.md
lib/secure_headers/configuration.rb
spec/lib/secure_headers/configuration_spec.rb
spec/spec_helper.rb

This PR changes the behavior of the `override` and `named_append` methods to raise an exception when it is called more than once with the same configuration name. This is to avoid unexpected behavior in case a configuration is used in some way in between two configuration declarations.
Fixes #435

Raise on override defined config

---

.github/workflows/build.yml
.github/workflows/sync.yml
CHANGELOG.md
README.md

One of the directives still uses a `master-only` value so I can't remove all (yet). The default branch for the repo has already been changed. 
This (should) keep `main` and `master` in sync just in case. I'll remove it soon after.

replace references to 'master' with 'main' to reflect new branch strategy

---

docs/upgrading-to-6-0.md

* Fix typo
* Improve header description about default configuration
* Titlecase "Ruby"
Let me know about any updates necessary. Thanks!

Minor improvements to 6.0 upgrade doc [ci skip]

---

README.md

In this repo's readme there is a link to: https://github.com/sourceclear/headlines
This is in section for "Similar libraries".
However that is a deadlink and gives Status code [404:NotFound].
Looking at https://github.com/sourceclear there does not appear to be any similar named repos belonging to them.
So I assume this is not a simple typo and that this repo has been removed.
Perhaps the simplest thing to do here is to just remove this "Similar libraries" reference all together?
So that is what I have done in this PR.
However please feel free to suggest an alternate approach.
I recently created a tool that makes use of the GitHub api to find repos that match certain parameters. Then this tool checks the repo's readme files for dead links: …

Deadlink in readme file in this repo to https://github.com/sourceclear/headlines which does not exist - Status code [404:NotFound]

---

README.md
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb

- Chrome, Edge, and Opera support them
- Safari, Firefox, and IE **don't** support these directives yet
- More info about these at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-attr
- These headers should allow any value that's valid for their parent directives `script_src` and `style_src`
- https://w3c.github.io/webappsec-csp/#directive-script-src-attr
- https://w3c.github.io/webappsec-csp/#directive-script-src-elem
- https://w3c.github.io/webappsec-csp/#directive-style-src-attr
- https://w3c.github.io/webappsec-csp/#directive-style-src-elem

Add missing CSP version 3 directives

---

lib/tasks/tasks.rake

The helper outputs the closing `</script>` or `</style>` unindented
if it is on its own line. Needed to remove any extra whitespace
the regex captures on that last line.
Honestly, I wasn't sure how to test this without also refactoring the entire rake task.
Didn't think any documentation needed to be updated since this is really just working better now.
Related to comments in #432, though maybe not the original issue.

Fix hash generation for indented helper methods

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

* Is the header supported by any user agent? If so, which? N/A
* What does it do? N/A
* What are the valid values for the header? N/A
* Where does the specification live? N/A
* Is the directive supported by any user agent? If so, which? N/A
* What does it do? N/A
* What are the valid values for the directive? N/A
This correct a bug in the `dedup_source_list` function, which causes sources with different protocols to be removed, which breaks possible CSP as headers as the spec only allows for _current protocol_ for schemaless source expressions.
Consider the following `connect-src: *.example.com wss://*.example.com`. This effectively allows for http and websocket connections. The current version of `secure_headers` will minify this to be …

do not dedupe alternate schema source expresions

---

lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb

This PR adds support for the [TrustedTypes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types) CSP directives, [`require-trusted-types-for`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for) and 'trusted-types'.
TrustedTypes are available in [Chrome 83, Edge 83](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types#browser_compatibility) and a [polyfill](https://github.com/w3c/webappsec-trusted-types#polyfill) exists for browsers that don't currently support.
`require-trusted-types-for` disallows using strings with DOM XSS [injection sink …

Add trusted-types and require-trusted-types-for CSP Directive

---

secure_headers.gemspec

Using an SPDX code makes automatic processing easier. The summary should be shorter than the description.
These are irrelevant since it's metadata.

Use SPDX license code and swap summary & description

---

secure_headers.gemspec

In https://github.com/github/secure_headers/pull/315 (5638cb03344a8b5f02024735143d2261cff08a94) the gem was relicensed to MIT, but it was incomplete. 86c762aea480d0a776246652586f93e026f6799f at least fixed the README, but the gemspec itself was still forgotten.
Follow up to https://github.com/github/secure_headers/pull/493#discussion_r942911282

Set license code in metadata to MIT

---

lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb

Unlike e.g. `require-sri-for` (which our previous implementation for), the `require-trusted-types-for` directive uses:
- Single-quoted `'script'` and `'none'` sources (in addition to `'allow-duplicates'`).
- Unquoted policies in addition to those.
See:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-sri-for
- https://w3c.github.io/webappsec-trusted-types/dist/spec/#require-trusted-types-for-csp-directive
Right now we are flexible about both quoted and unquoted sources, but this PR starts by using the values used for the directive per spec / browser implementations.

Trusted types: Use single-quoted `'script'`.

---

.github/workflows/build.yml

Ruby 2.5 has been failing on CI since https://github.com/github/secure_headers/pull/499 and is no longer supported.

CI changes: run on push, drop Ruby 2.5

---

lib/secure_headers/headers/content_security_policy.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb

This PR removes `dedup_source_list` and replaces it with a simple `.uniq` call. This resolves https://github.com/github/secure_headers/issues/491, which is only the latest in a series of ongoing issues with source expression deduplication.
`secure_headers` has had this feature [since 2015](https://github.com/github/secure_headers/commit/32bb3f51e8d877baf1e3e4461663ae0b7b1347c0) that [deduplicates redundant URL source expressions](https://github.com/github/secure_headers/blob/494b75ff927464ed8d1c43e98e41fe4d15ce2bdf/lib/secure_headers/headers/content_security_policy.rb#L157-L170). For example, if `*.github.com` is listed as a source expression for a given [directive](https://w3c.github.io/webappsec-csp/#framework-directives), then the addition of `example.github.com` would have no effect, …

Remove source expression deduplication.

---

README.md
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/policy_management.rb
spec/lib/secure_headers/headers/content_security_policy_spec.rb
spec/lib/secure_headers/headers/policy_management_spec.rb

* update tests and readme to reflect this change
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content:x

deprecate block-all-mixed-content

---

Gemfile
lib/secure_headers/configuration.rb
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/content_security_policy_config.rb

We have been seeing this gem a lot in profiles. Must of this slowness seems to come from overuse of instance variables in `DynamicConfig` and attempting to use them basically as a hash (which we can do much faster with a hash 😅)
The first commit of these is the most important, but the other two also significantly speed things up.
There is definitely more improvement available here, we seem to be overly cautious in duplicating arrays, and we also seem to convert unnecessarily between hashes and the config object, but I think this is the best place to start.
<details>
<summary>Benchmark:</summary>
```
require "secure_headers"
require "benchmark/ips"
MyCSPConfig = SecureHeaders::ContentSecurityPolicyConfig.new(
preserve_schemes: true, # default: false. Schemes are removed from host sources …
```

Make SecureSecurityPolicyConfig significantly faster

---

CHANGELOG.md
README.md
docs/hashes.md
docs/per_action_configuration.md
docs/upgrading-to-4-0.md
lib/secure_headers/configuration.rb
lib/secure_headers/headers/clear_site_data.rb
lib/secure_headers/headers/content_security_policy.rb
lib/secure_headers/headers/content_security_policy_config.rb
lib/secure_headers/headers/expect_certificate_transparency.rb
lib/secure_headers/headers/policy_management.rb
lib/secure_headers/headers/referrer_policy.rb
lib/secure_headers/headers/strict_transport_security.rb
lib/secure_headers/headers/x_content_type_options.rb
lib/secure_headers/headers/x_download_options.rb
lib/secure_headers/headers/x_frame_options.rb
lib/secure_headers/headers/x_permitted_cross_domain_policies.rb
lib/secure_headers/headers/x_xss_protection.rb
lib/secure_headers/railtie.rb
spec/lib/secure_headers_spec.rb

* Is the header supported by any user agent? If so, which?
* What are the valid values for the header?
---
Rack 3 `Response header keys can no longer include uppercase characters.`
https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#rack-3-upgrade-guide
Rack Lint error out when using `secure_headers` because its adding headers with uppercase
```
Rack::Lint::LintError: uppercase character in header name: X-Frame-Options (Rack::Lint::LintError)
```

Lowercase headers
