github/secure_headers

lib/secure_headers/headers/content_security_policy.rb
=> Add :report_uri to list of directives

README.md
Update NWebsec url to the new project page.
=> update NWebsec url

lib/secure_headers/headers/content_security_policy.rb, spec/lib/secure_headers/headers/content_security_policy_spec.rb
I'm taking over https://github.com/twitter/secureheaders/pull/159 for @rbhitchcock
=> Allow user to disable auto data uri whitelist 

README.md
Fix minor typo in README example.
=> Fix typo contoller > controller

README.md, fixtures/rails_3_2_22/config/initializers/secure_headers.rb, fixtures/rails_3_2_22_no_init/app/controllers/other_things_controller.rb, fixtures/rails_4_1_8/config/initializers/secure_headers.rb, lib/secure_headers/headers/content_security_policy.rb, spec/lib/secure_headers/headers/content_security_policy_spec.rb
Fixes https://github.com/twitter/secureheaders/issues/170
Also removes tons of deprecation warnings.
=> Directive cleanup

lib/secure_headers/headers/content_security_policy.rb
Thanks to @igrep for pointing this out.
Fixes #187
=> Cache UserAgentParser instance

README.md, upgrading-to-3-0.md
I'll continue to update this since I've likely left things out, but it's a start and the 3.x branch hasn't even been released yet.
=> instructions on upgrading to 3.x

README.md, lib/secure_headers.rb, spec/lib/secure_headers/headers/content_security_policy_spec.rb, spec/lib/secure_headers/headers/public_key_pins_spec.rb, spec/lib/secure_headers_spec.rb
* Ruby 1.8 has not been supported for years
=> Use clean ruby hash syntax

README.md
=> Remove duplicate configuration example

README.md
just found this on the interwebs :smile_cat:
=> add link to dropwizard-web-security

README.md
=> add link to ember-cli-content-security-policy

CHANGELOG.md
=> Fix missing ``` in changelog

spec/lib/secure_headers_spec.rb
Just adding some small test cases, I felt that the undefined override test was important since it's part of the public API. The cookies config is covered as a unit test elsewhere but I added the test here for consistency with the other policies. 😄
=> Additional tests

lib/secure_headers/headers/policy_management.rb, spec/lib/secure_headers/headers/content_security_policy_spec.rb, spec/spec_helper.rb
=> filter unsupported Edge directives

README.md
=> update x-frame-options link to RFC

README.md, spec/lib/secure_headers/headers/policy_management_spec.rb
=> wws: -> wss:

README.md
This PR updates a minor change in documentation of domain used in example.
* Is the header supported by any user agent? If so, which?
* What are the valid values for the header?
=> Minor change in domain

lib/secure_headers/view_helper.rb, spec/lib/secure_headers/view_helpers_spec.rb
=> add content_security_policy_script/style_nonce to view helper

lib/secure_headers/headers/referrer_policy.rb, spec/lib/secure_headers/headers/referrer_policy_spec.rb
* Is the header supported by any user agent? If so, which?
* What are the valid values for the header?
* Add same-origin, strict-origin and strict-origin-when-cross-origin
=> Add missing Referrer Policies

.travis.yml
=> Add Ruby 2.3 and 2.4 to test matrix.

.travis.yml
=> Remove unsupported rubies

README.md, docs/per_action_configuration.md, lib/secure_headers/headers/clear_site_data.rb
This PR contains
1) Word of caution about configuration.(A lot of people including me misunderstood the given configuration to be default configuration)
2) Added relevant documentation to use clear_site_data headers on specific requests.
=> Updates to documentation to clarify the default configuration misunderstanding.

secure_headers.gemspec
=> the same URL is repeated twice in the gemspec

lib/secure_headers/version.rb, secure_headers.gemspec
This should fix up the linter CI problems encountered by @will ran into in https://github.com/twitter/secure_headers/pull/404
=> clean up some linter errors showing up in newer CI

docs/cookies.md, lib/secure_headers/headers/cookie.rb, lib/secure_headers/utils/cookies_config.rb, spec/lib/secure_headers/headers/cookie_spec.rb
Backport #414 to the 3.x branch.
=> Add support for SameSite=None to 3.x

README.md
This is at the request of @agargenta prior to handoff.
=> add Twitter and early contributors up to 2015 or so to README

README.md
=> Add twitter-archive fork reference

.github/workflows/build.yml
=> Update ruby build scripts and bump test matrix versions

docs/per_action_configuration.md
Fix for the ClearSiteData example so that it works.
* [n/a] Has tests
* Is the header supported by any user agent? If so, which?
* What are the valid values for the header?
=> Fix ClearSiteData example

.github/workflows/build.yml, lib/secure_headers/configuration.rb, lib/secure_headers/headers/content_security_policy.rb, lib/secure_headers/headers/policy_management.rb, lib/secure_headers/view_helper.rb, spec/lib/secure_headers/view_helpers_spec.rb
Also made several formatting changes to get Rubocop to be green.
* Has tests - N/A as this is a CI configuration change
* Documentation updated- N/A as this is a CI configuration change
=> Add Ruby 3.1 to the CI configuration

CHANGELOG.md, lib/secure_headers/version.rb
Updating to minor version 6.4.0 to include trusted-types directive
=> update version and changelog

.github/workflows/build.yml, lib/secure_headers/headers/cookie.rb
Also updated the checkout action version.
To get the tests to pass, I needed to address a couple of minor lints.
=> Adds Ruby 3.2 to the CI matrix

docs/upgrading-to-7-0.md, lib/secure_headers/version.rb, secure_headers.gemspec
N/A
N/A
Closes https://github.com/github/secure_headers/issues/480
=> Upgrade version and docs to 7.0
